"use client";

import { useEffect, useState } from "react";
import { Icon, Workspace } from "../components/workspace";

type Finding = { id: string; severity: string; title: string; evidence: string };
type BrokenLink = { id: string; source_page: string; label: string; destination: string; status_code: number; error?: string; link_type: string; element: string; severity: string };
type Contact = { id: string; email: string; source_url: string; kind: string; confidence: number };
type PageSpeed = { strategy: string; performance?: number; accessibility?: number; best_practices?: number; seo?: number; lcp_ms?: number; cls?: number; inp_ms?: number; ttfb_ms?: number; error_message?: string };
type Audit = { id: string; lead: { business_name: string }; requested_url: string; final_url: string; http_status: number; response_time_ms: number; uses_https: boolean; score: number; status: string; findings: Finding[]; pages: { id: string; url: string; status_code: number; title: string; depth: number }[]; broken_links: BrokenLink[]; contacts: Contact[]; pagespeed?: PageSpeed; created_at: string };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080/api/v1";

export default function AuditsPage() {
  const [audits, setAudits] = useState<Audit[]>([]), [selected, setSelected] = useState<Audit | null>(null);
  const [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let cancelled = false; fetch(`${API}/audits`, { cache: "no-store" }).then(async r => { const b = await r.json(); if (!r.ok) throw new Error(b.error); return b; }).then(b => { if (!cancelled) { setAudits(b.data ?? []); setSelected(b.data?.[0] ?? null); } }).catch(e => { if (!cancelled) setError(e instanceof Error ? e.message : "Could not load website audits."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  return <Workspace active="Website audits"><div className="page audit-page">
    <section className="leads-heading"><div><h1>Website audits</h1><p>Technical evidence collected from public business websites.</p></div></section>
    <div className="safety-banner"><span><Icon name="shield" /></span><div><strong>Evidence, not AI opinion</strong><p>Every finding comes from a deterministic check. Private networks and internal URLs are blocked.</p></div></div>
    {error && <div className="api-error"><span>{error}</span></div>}
    <section className="audit-layout"><div className="audit-list-panel"><div className="audit-list-head"><strong>Recent audits</strong><span>{audits.length} total</span></div>{loading ? <div className="empty-result"><strong>Loading audits…</strong></div> : audits.length === 0 ? <div className="empty-result"><Icon name="audit" size={22} /><strong>No audits completed</strong><p>Run an audit from Leads.</p></div> : audits.map(a => <button key={a.id} onClick={() => setSelected(a)} className={`audit-list-item ${selected?.id === a.id ? "selected" : ""}`}><span className={`audit-score score-${a.score < 50 ? "low" : a.score < 75 ? "mid" : "good"}`}>{a.score}</span><div><strong>{a.lead?.business_name ?? "Business"}</strong><p>{a.findings.length} findings · {a.pages?.length ?? 0} pages</p></div><span className="audit-date">{new Date(a.created_at).toLocaleDateString("en-NG", { month: "short", day: "numeric" })}</span><Icon name="arrow" /></button>)}</div>
      <div className="audit-detail">{selected ? <><div className="audit-detail-head"><div><span className="detail-label">AUDIT REPORT</span><h2>{selected.lead?.business_name ?? "Business"}</h2><p>{selected.final_url || selected.requested_url}</p></div><span className={`big-score score-${selected.score < 50 ? "low" : selected.score < 75 ? "mid" : "good"}`}><strong>{selected.score}</strong><small>/ 100</small></span></div>
        <div className="audit-signals"><div><span>HTTP status</span><strong>{selected.http_status || "—"}</strong></div><div><span>Response time</span><strong>{selected.response_time_ms} ms</strong></div><div><span>HTTPS</span><strong>{selected.uses_https ? "Enabled" : "Missing"}</strong></div><div><span>Pages checked</span><strong>{selected.pages?.length ?? 0}</strong></div><div><span>Broken links</span><strong>{selected.broken_links?.length ?? 0}</strong></div></div>
        <h3 className="findings-title">Verified findings</h3><div className="finding-list">{selected.findings.length ? selected.findings.map(f => <article key={f.id}><span className={`severity ${f.severity}`}>{f.severity}</span><div><strong>{f.title}</strong><p>{f.evidence}</p></div></article>) : <div className="clean-audit"><Icon name="check" /><strong>No issues found by current checks</strong></div>}</div>
        {selected.pagespeed && <section className="audit-report-section"><div className="report-heading"><div><h3>PageSpeed Insights</h3><p>Mobile Lighthouse evidence, captured separately from the custom crawler.</p></div><span>{selected.pagespeed.strategy}</span></div><div className="pagespeed-grid">{[["Performance", selected.pagespeed.performance], ["Accessibility", selected.pagespeed.accessibility], ["Best practices", selected.pagespeed.best_practices], ["SEO", selected.pagespeed.seo]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{typeof value === "number" ? Math.round(value) : "—"}</strong></div>)}</div><div className="web-vitals"><span>LCP {selected.pagespeed.lcp_ms ? `${Math.round(selected.pagespeed.lcp_ms)} ms` : "—"}</span><span>CLS {typeof selected.pagespeed.cls === "number" ? selected.pagespeed.cls.toFixed(2) : "—"}</span><span>INP {selected.pagespeed.inp_ms ? `${Math.round(selected.pagespeed.inp_ms)} ms` : "—"}</span><span>TTFB {selected.pagespeed.ttfb_ms ? `${Math.round(selected.pagespeed.ttfb_ms)} ms` : "—"}</span></div></section>}
        {Boolean(selected.broken_links?.length) && <section className="audit-report-section"><div className="report-heading"><div><h3>Broken-link report</h3><p>Source page, label, destination, and response.</p></div><span>{selected.broken_links.length}</span></div>{selected.broken_links.map(link => <article className="broken-link-row" key={link.id}><div className="broken-link-top"><span className={`severity ${link.severity}`}>{link.severity}</span><strong>{link.label || "Unlabelled link"}</strong><code>{link.status_code || "ERR"}</code></div><dl><div><dt>Found on</dt><dd>{link.source_page}</dd></div><div><dt>Destination</dt><dd>{link.destination}</dd></div><div><dt>Element</dt><dd>{link.element} · {link.link_type}</dd></div>{link.error && <div><dt>Error</dt><dd>{link.error}</dd></div>}</dl></article>)}</section>}
        {Boolean(selected.contacts?.length) && <section className="audit-report-section"><div className="report-heading"><div><h3>Public contact evidence</h3><p>Addresses discovered on public business pages.</p></div><span>{selected.contacts.length}</span></div>{selected.contacts.map(contact => <article className="contact-evidence-row" key={contact.id}><div><strong>{contact.email}</strong><p>{contact.kind} · {contact.confidence}% confidence · {contact.source_url}</p></div><a href={contact.source_url} target="_blank" rel="noreferrer">View source</a></article>)}</section>}
      </> : <div className="audit-placeholder"><Icon name="audit" size={24} /><strong>Select an audit</strong><p>Review measured signals and exact evidence.</p></div>}</div></section>
  </div></Workspace>;
}
