"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Icon, Workspace } from "../components/workspace";

type Lead = { id:string; business_name:string; category:string; location:string; website_url:string; public_email:string; website_score:number|null; status:string; source:string; created_at:string };
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080/api/v1";
const statusLabel = (value:string) => ({new:"New",ready_for_review:"Ready for review",auditing:"Auditing",draft_ready:"Draft ready",replied:"Replied"}[value] ?? value);
const sourceLabel = (value:string) => value.split("_").map(v=>v[0].toUpperCase()+v.slice(1)).join(" ");
const initials = (name:string) => name.split(/\s+/).slice(0,2).map(v=>v[0]).join("").toUpperCase();

export default function LeadsPage() {
  const [records,setRecords]=useState<Lead[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [query,setQuery]=useState(""); const [tab,setTab]=useState("all"); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [auditing,setAuditing]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`${API}/leads`,{cache:"no-store"});if(!response.ok)throw new Error();const body=await response.json();setRecords(body.data??[])}catch{setError("Could not connect to the LeadForge API. Start MySQL and the Go server, then try again.")}finally{setLoading(false)}},[]);
  useEffect(()=>{let cancelled=false;fetch(`${API}/leads`,{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(body=>{if(!cancelled)setRecords(body.data??[])}).catch(()=>{if(!cancelled)setError("Could not connect to the LeadForge API. Start MySQL and the Go server, then try again.")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
  const filtered=useMemo(()=>records.filter(r=>(tab==="all"||r.status===tab)&&`${r.business_name} ${r.category} ${r.location}`.toLowerCase().includes(query.toLowerCase())),[records,query,tab]);
  const runAudit=async(lead:Lead)=>{if(!lead.website_url)return;setAuditing(lead.id);setError("");setRecords(items=>items.map(item=>item.id===lead.id?{...item,status:"auditing"}:item));try{const response=await fetch(`${API}/leads/${lead.id}/audits`,{method:"POST"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Audit could not be completed");setRecords(items=>items.map(item=>item.id===lead.id?{...item,status:"ready_for_review",website_score:body.data.score}:item))}catch(reason){setRecords(items=>items.map(item=>item.id===lead.id?{...item,status:lead.status}:item));setError(reason instanceof Error?reason.message:"Audit could not be completed")}finally{setAuditing(null)}};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch(`${API}/leads`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const body=await response.json();if(!response.ok)throw new Error(body.error??"Could not save lead");setRecords(items=>[body.data,...items]);setOpen(false)}catch(reason){setError(reason instanceof Error?reason.message:"Could not save lead")}finally{setSaving(false)}};

  return <Workspace active="Leads" onAdd={()=>setOpen(true)}><div className="page leads-page">
    <section className="leads-heading"><div><h1>Leads</h1><p>Businesses you added for research and review.</p></div><div className="heading-actions"><button className="secondary-button"><Icon name="upload"/> Import CSV</button><button className="primary-button" onClick={()=>setOpen(true)}><Icon name="plus"/> Add lead</button></div></section>
    <div className="safety-banner"><span><Icon name="shield"/></span><div><strong>You control every outreach action</strong><p>Website audits collect public technical evidence only. They never contact the business.</p></div></div>
    {error&&<div className="api-error"><span>{error}</span><button onClick={()=>void load()}>Try again</button></div>}
    <section className="leads-panel">
      <div className="lead-tabs">{[["all","All leads"],["new","New"],["ready_for_review","Ready for review"],["auditing","Auditing"],["draft_ready","Draft ready"],["replied","Replied"]].map(([value,label])=><button key={value} onClick={()=>setTab(value)} className={tab===value?"selected":""}>{label}<span>{value==="all"?records.length:records.filter(r=>r.status===value).length}</span></button>)}</div>
      <div className="lead-toolbar"><label><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search leads..."/></label><button className="secondary-button compact"><Icon name="filter"/> Filter</button><span className="result-count">{filtered.length} leads</span></div>
      <div className="table-wrap lead-table"><table><thead><tr><th>Business</th><th>Website</th><th>Contact</th><th>Score</th><th>Status</th><th>Source</th><th>Added</th><th>Research</th></tr></thead><tbody>{filtered.map((lead,index)=><tr key={lead.id}>
        <td><Link href={`/leads/${lead.id}`} className="business-cell business-link"><span style={{background:["#d9e7dc","#dce7f2","#eee4d5","#e8dfea"][index%4]}}>{initials(lead.business_name)}</span><div><strong>{lead.business_name}</strong><p>{lead.category||"Uncategorized"} · {lead.location||"Location not added"}</p></div></Link></td>
        <td><span className="website-link"><Icon name="globe" size={13}/>{lead.website_url?lead.website_url.replace(/^https?:\/\//,""):"No website added"}</span></td><td className={!lead.public_email?"muted":""}>{lead.public_email||"Public email not added"}</td>
        <td>{lead.website_score===null?<span className="muted">—</span>:<div className="score"><span className={lead.website_score<45?"low":"medium"}>{lead.website_score}</span></div>}</td><td><span className={`lead-status ${statusLabel(lead.status).toLowerCase().replaceAll(" ","-")}`}>{statusLabel(lead.status)}</span></td><td className="muted">{sourceLabel(lead.source)}</td><td className="muted">{new Date(lead.created_at).toLocaleDateString("en-NG",{month:"short",day:"numeric"})}</td>
        <td><div className="research-actions"><button className="audit-row-action" disabled={!lead.website_url||auditing===lead.id} onClick={()=>void runAudit(lead)}>{auditing===lead.id?"Auditing…":lead.website_score===null?"Run audit":"Run again"}</button>{lead.website_score!==null&&<Link href={`/audits?lead_id=${lead.id}`}>History</Link>}</div></td>
      </tr>)}</tbody></table>{loading?<div className="empty-result"><strong>Loading leads…</strong></div>:filtered.length===0&&<div className="empty-result"><Icon name="search" size={20}/><strong>{records.length?"No leads found":"No businesses yet"}</strong><p>{records.length?"Try another search or status.":"Add a business to begin supervised research."}</p></div>}</div>
    </section>
  </div>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="lead-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>Add a business</h2><p>We’ll research the website only when you request an audit.</p></div><button onClick={()=>setOpen(false)}><Icon name="close"/></button></div><form onSubmit={submit}><label className="field">Business name <span>Required</span><input name="business_name" required placeholder="e.g. Kora Medical"/></label><div className="field-row"><label className="field">Website URL <span>Optional</span><input name="website_url" placeholder="https://example.com"/></label><label className="field">Location <span>Optional</span><input name="location" placeholder="Lagos, Nigeria"/></label></div><label className="field">Category <span>Optional</span><input name="category" placeholder="e.g. Private clinic"/></label><label className="field">Public business email <span>Optional</span><input name="public_email" type="email" placeholder="hello@example.com"/><small>Only enter an address the business publishes for contact.</small></label><label className="field">Source <span>Required</span><select name="source" required defaultValue=""><option value="" disabled>Where did you find this business?</option><option value="manual_research">Manual research</option><option value="referral">Referral</option><option value="public_directory">Public business directory</option><option value="existing_relationship">Existing relationship</option></select></label><div className="modal-safety"><Icon name="shield"/><p><strong>Research only.</strong> Saving this business does not run an audit or start outreach.</p></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button disabled={saving} className="primary-button">{saving?"Saving…":"Save business"}</button></div></form></div></div>}</Workspace>;
}
